#define TOOLKIT_KEY_SPACE       SDLK_SPACE
#define TOOLKIT_KEY_LSHIFT      SDLK_LSHIFT
#define TOOLKIT_KEY_RSHIFT      SDLK_RSHIFT
#define TOOLKIT_KEY_LCTRL       SDLK_LCTRL
#define TOOLKIT_KEY_RCTRL       SDLK_RCTRL
#define TOOLKIT_KEY_LALT        SDLK_LALT
#define TOOLKIT_KEY_RALT        SDLK_RALT
#define TOOLKIT_KEY_UP          SDLK_UP
#define TOOLKIT_KEY_DOWN        SDLK_DOWN
#define TOOLKIT_KEY_LEFT        SDLK_LEFT
#define TOOLKIT_KEY_RIGHT       SDLK_RIGHT
#define TOOLKIT_KEY_BACK        SDLK_BACKSPACE
#define TOOLKIT_KEY_RETURN      SDLK_RETURN
#define TOOLKIT_KEY_PAGEUP      SDLK_PAGEUP
#define TOOLKIT_KEY_PAGEDOWN    SDLK_PAGEDOWN
#define TOOLKIT_KEY_HOME        SDLK_HOME
#define TOOLKIT_KEY_END         SDLK_END
#define TOOLKIT_KEY_INSERT      SDLK_INSERT
#define TOOLKIT_KEY_DELETE      SDLK_DELETE
#define TOOLKIT_KEY_PAUSE       SDLK_PAUSE
#define TOOLKIT_KEY_MENU        SDLK_MENU
#define TOOLKIT_KEY_LSUPER      SDLK_LGUI
#define TOOLKIT_KEY_RSUPER      SDLK_RGUI
#define TOOLKIT_KEY_PRTSC       SDLK_PRINTSCREEN
#define TOOLKIT_KEY_TAB         SDLK_TAB
#define TOOLKIT_KEY_ESC         SDLK_ESCAPE
#define TOOLKIT_KEY_COMMA       SDLK_COMMA
#define TOOLKIT_KEY_PERIOD      SDLK_PERIOD
#define TOOLKIT_KEY_SLASH       SDLK_SLASH
#define TOOLKIT_KEY_NUM_LOCK    SDLK_NUMLOCKCLEAR
#define TOOLKIT_KEY_CAPS_LOCK   SDLK_CAPSLOCK
#define TOOLKIT_KEY_SCROLL_LOCK SDLK_SCROLLLOCK
#define TOOLKIT_KEY_1           SDLK_1
#define TOOLKIT_KEY_2           SDLK_2
#define TOOLKIT_KEY_3           SDLK_3
#define TOOLKIT_KEY_4           SDLK_4
#define TOOLKIT_KEY_5           SDLK_5
#define TOOLKIT_KEY_6           SDLK_6
#define TOOLKIT_KEY_7           SDLK_7
#define TOOLKIT_KEY_8           SDLK_8
#define TOOLKIT_KEY_9           SDLK_9
#define TOOLKIT_KEY_A           SDLK_a
#define TOOLKIT_KEY_B           SDLK_b
#define TOOLKIT_KEY_C           SDLK_c
#define TOOLKIT_KEY_D           SDLK_d
#define TOOLKIT_KEY_E           SDLK_e
#define TOOLKIT_KEY_F           SDLK_f
#define TOOLKIT_KEY_G           SDLK_g
#define TOOLKIT_KEY_H           SDLK_h
#define TOOLKIT_KEY_I           SDLK_i
#define TOOLKIT_KEY_J           SDLK_j
#define TOOLKIT_KEY_K           SDLK_k
#define TOOLKIT_KEY_L           SDLK_l
#define TOOLKIT_KEY_M           SDLK_m
#define TOOLKIT_KEY_N           SDLK_n
#define TOOLKIT_KEY_O           SDLK_o
#define TOOLKIT_KEY_P           SDLK_p
#define TOOLKIT_KEY_Q           SDLK_q
#define TOOLKIT_KEY_R           SDLK_r
#define TOOLKIT_KEY_S           SDLK_s
#define TOOLKIT_KEY_T           SDLK_t
#define TOOLKIT_KEY_U           SDLK_u
#define TOOLKIT_KEY_V           SDLK_v
#define TOOLKIT_KEY_W           SDLK_w
#define TOOLKIT_KEY_X           SDLK_x
#define TOOLKIT_KEY_Y           SDLK_y
#define TOOLKIT_KEY_Z           SDLK_z
#define TOOLKIT_KEY_F1          SDLK_F1
#define TOOLKIT_KEY_F2          SDLK_F2
#define TOOLKIT_KEY_F3          SDLK_F3
#define TOOLKIT_KEY_F4          SDLK_F4
#define TOOLKIT_KEY_F5          SDLK_F5
#define TOOLKIT_KEY_F6          SDLK_F6
#define TOOLKIT_KEY_F7          SDLK_F7
#define TOOLKIT_KEY_F8          SDLK_F8
#define TOOLKIT_KEY_F9          SDLK_F9
#define TOOLKIT_KEY_F10         SDLK_F10
#define TOOLKIT_KEY_F11         SDLK_F11
#define TOOLKIT_KEY_F12         SDLK_F12
#define TOOLKIT_KEY_F13         SDLK_F13
#define TOOLKIT_KEY_F14         SDLK_F14
#define TOOLKIT_KEY_F15         SDLK_F15
#define TOOLKIT_KEY_F16         SDLK_F16
#define TOOLKIT_KEY_F17         SDLK_F17
#define TOOLKIT_KEY_F18         SDLK_F18
#define TOOLKIT_KEY_F19         SDLK_F19
#define TOOLKIT_KEY_F20         SDLK_F20
#define TOOLKIT_KEY_F21         SDLK_F21
#define TOOLKIT_KEY_F22         SDLK_F22
#define TOOLKIT_KEY_F23         SDLK_F23
#define TOOLKIT_KEY_F24         SDLK_F24
#define TOOLKIT_KEY_KP_0        SDLK_KP_0
#define TOOLKIT_KEY_KP_1        SDLK_KP_1
#define TOOLKIT_KEY_KP_2        SDLK_KP_2
#define TOOLKIT_KEY_KP_3        SDLK_KP_3
#define TOOLKIT_KEY_KP_4        SDLK_KP_4
#define TOOLKIT_KEY_KP_5        SDLK_KP_5
#define TOOLKIT_KEY_KP_6        SDLK_KP_6
#define TOOLKIT_KEY_KP_7        SDLK_KP_7
#define TOOLKIT_KEY_KP_8        SDLK_KP_8
#define TOOLKIT_KEY_KP_9        SDLK_KP_9
#define TOOLKIT_KEY_KP_ADD      SDLK_KP_PLUS
#define TOOLKIT_KEY_KP_SUBTRACT SDLK_KP_MINUS
#define TOOLKIT_KEY_KP_MULTIPLY SDLK_KP_MULTIPLY
#define TOOLKIT_KEY_KP_DIVIDE   SDLK_KP_DIVIDE
#define TOOLKIT_KEY_KP_EQUAL    SDLK_KP_EQUALS
#define TOOLKIT_KEY_KP_ENTER    SDLK_KP_ENTER